package com.example.motionlab.data.local.db

import android.content.Context
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.motionlab.R
import com.example.motionlab.data.local.entity.LessonEntity
import com.example.motionlab.data.local.entity.MaterialType
import com.example.motionlab.data.local.entity.QuestionEntity
import com.example.motionlab.data.local.entity.SubtopicEntity
import com.example.motionlab.data.local.entity.SubtopicMaterialEntity
import com.example.motionlab.domain.model.local.QuestionJson
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch


class LessonDatabaseCallback(
    private val scope: CoroutineScope,
    private val context: Context
) : RoomDatabase.Callback() {

    override fun onCreate(db: SupportSQLiteDatabase) {
        super.onCreate(db)


        scope.launch(Dispatchers.IO) {
            val lessonDao = AppDatabase.instance?.lessonDao() ?: return@launch
            val subtopicDao = AppDatabase.instance?.subtopicDao() ?: return@launch
            val questionDao = AppDatabase.instance?.questionDao() ?: return@launch
            val materialDao = AppDatabase.instance?.subtopicMaterialDao() ?: return@launch

            // 1. Insert lessons
            val sampleLessons = listOf(
                LessonEntity(
                    title = "Mechanics",
                    description = "Mechanics is the branch of physics that studies motion and the forces acting on objects.",
                    iconRes = R.drawable.mechanics
                ),
                LessonEntity(
                    title = "Newton’s Laws of Motion",
                    description = "Newton's three laws of motion explain how objects move and respond to forces: objects stay at rest or in constant motion unless acted on, force equals mass times acceleration, " +
                            "and every action has an equal and opposite reaction.",
                    iconRes = R.drawable.newtons_law
                ),
                LessonEntity(
                    title = "Work, Power, & Energy",
                    description = "In physics, work is the force applied over a distance, power is the rate at which work is done, and energy is the capacity to do work, existing in forms like kinetic and potential energy.",
                    iconRes = R.drawable.work_power_energy
                )
            )

            lessonDao.insertLessons(sampleLessons)

            // 2. Reload lessons to get autogenerated IDs
            val lessons = lessonDao.getAllLessons()

            val mechanicsId = lessons.find { it.title == "Mechanics" }?.lessonId ?: return@launch
            val newtonId = lessons.find { it.title == "Newton’s Laws of Motion" }?.lessonId ?: return@launch
            val workPowerEnergyId = lessons.find { it.title == "Work, Power, & Energy" }?.lessonId ?: return@launch

            // 3. Subtopics for Mechanics
            val mechanicsSubtopics = listOf(
                SubtopicEntity(
                    lessonId = mechanicsId,
                    title = "Uniformly Accelerated Motion",
                    iconRes = R.drawable.uam,
                    content = "Uniformly Accelerated Motion (UAM) is motion under constant acceleration. This includes objects in free fall.",
                    order = 0
                ),
                SubtopicEntity(
                    lessonId = mechanicsId,
                    title = "Projectile Motion",
                    iconRes = R.drawable.projectile_motion,
                    content = "Projectile motion is a form of motion where an object moves in a curved trajectory under gravity.",
                    order = 1
                ),
                SubtopicEntity(
                    lessonId = mechanicsId,
                    title = "Momentum",
                    iconRes = R.drawable.momentum,
                    content = "Momentum is the product of mass and velocity and is conserved in closed systems.",
                    order = 2
                )
            )

            // 4. Subtopics for Newton’s Laws
            val newtonSubtopics = listOf(
                SubtopicEntity(
                    lessonId = newtonId,
                    title = "Law of Inertia",
                    iconRes = R.drawable.law1,
                    content = "An object will remain at rest or move in a straight line unless acted upon by an external force.",
                    videoUrl = "",
                    order = 0
                ),
                SubtopicEntity(
                    lessonId = newtonId,
                    title = "Force = Mass x Acceleration",
                    iconRes = R.drawable.law2,
                    content = "The acceleration of an object depends on the net force and the object’s mass.",
                    videoUrl = "",
                    order = 1
                ),
                SubtopicEntity(
                    lessonId = newtonId,
                    title = "Action-Reaction",
                    iconRes = R.drawable.law3,
                    content = "For every action, there is an equal and opposite reaction.",
                    videoUrl = "",
                    order = 2
                )
            )

            // 5. Subtopics for Work & Energy
            val energySubtopics = listOf(
                SubtopicEntity(
                    lessonId = workPowerEnergyId,
                    title = "Work",
                    iconRes = R.drawable.work,
                    content = "Work is done when a force is applied over a distance. Power is the rate at which work is done.",
                    videoUrl = "",
                    order = 0
                ),
                SubtopicEntity(
                    lessonId = workPowerEnergyId,
                    title = "Power",
                    iconRes = R.drawable.power,
                    content = "Kinetic energy is due to motion, and potential energy is stored due to position.",
                    videoUrl = "",
                    order = 1
                ),
                SubtopicEntity(
                    lessonId = workPowerEnergyId,
                    title = "Energy",
                    iconRes = R.drawable.energy,
                    content = "Energy cannot be created or destroyed, only transformed from one form to another.",
                    videoUrl = "",
                    order = 2
                )
            )

            // Insert all subtopics title, description and icon
            subtopicDao.insertSubtopics(mechanicsSubtopics + newtonSubtopics + energySubtopics)

            // Insert subtopic materials
            val insertedSubtopics = subtopicDao.getAllSubtopics()
            val materials = mutableListOf<SubtopicMaterialEntity>()

            // Mechanics Subtopics (ALL THREE MATERIALS FOR EACH)
            val mechanicsTitles = listOf("Uniformly Accelerated Motion", "Projectile Motion", "Momentum")
            insertedSubtopics.filter { it.title in mechanicsTitles }.forEach { subtopic ->
                val fileBase = subtopic.title.lowercase()
                    .replace(" ", "_")
                    .replace(Regex("[^a-z0-9_]+"), "")
                
                // Map to correct JSON file names
                val jsonFileName = when (subtopic.title) {
                    "Uniformly Accelerated Motion" -> "hands_on_uam"
                    "Projectile Motion" -> "hands_on_pm"
                    "Momentum" -> "hands_on_momentum"
                    else -> "hands_on_$fileBase"
                }
                
                // Map to correct video file names
                val videoFileName = when (subtopic.title) {
                    "Uniformly Accelerated Motion" -> "uam"
                    "Projectile Motion" -> "projectile_motion"
                    "Momentum" -> "momentum"
                    else -> fileBase
                }

                // Map to correct transcript JSON file names
                val transcriptFileName = when (subtopic.title) {
                    "Uniformly Accelerated Motion" -> "videoTranscripts/transcript_uam.json"
                    "Projectile Motion" -> "videoTranscripts/transcript_pm.json"
                    "Momentum" -> "videoTranscripts/transcript_momentum.json"
                    else -> "videoTranscripts/transcript_$fileBase.json"
                }
                
                println("Generated JSON path for '${subtopic.title}': exercises/$jsonFileName.json")
                println("Generated video path for '${subtopic.title}': raw/$videoFileName")
                println("Full video URI: android.resource://${context.packageName}/raw/$videoFileName")

                materials.addAll(
                    listOf(
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.VIDEO,
                            title = subtopic.title,
                            contentPath = "android.resource://${context.packageName}/raw/$videoFileName",
                            transcript = transcriptFileName
                        ),
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.HANDS_ON,
                            title = "${subtopic.title} Exercise",
                            contentPath = "exercises/$jsonFileName.json"
                        ),
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.SIMULATION,
                            title = "${subtopic.title} Simulation",
                            contentPath = "simulations/${fileBase}_sim.json"
                        )
                    )
                )
            }

            // 🧪 Newton's Laws (Hands-on, Simulation, and Videos)
            val newtonTitles = listOf("Law of Inertia", "Force = Mass x Acceleration", "Action-Reaction")
            insertedSubtopics.filter { it.title in newtonTitles }.forEach { subtopic ->
                val fileBase = subtopic.title.lowercase()
                    .replace("=", "equals")
                    .replace(" ", "_")
                    .replace(Regex("[^a-z0-9_]+"), "")

                // Map to correct JSON file names
                val jsonFileName = when (subtopic.title) {
                    "Law of Inertia" -> "hands_on_law_of_inertia"
                    "Force = Mass x Acceleration" -> "hands_on_force_equals_mass_x_acceleration"
                    "Action-Reaction" -> "hands_on_actionreaction"
                    else -> "hands_on_$fileBase"
                }
                
                // Map to correct video file names
                val videoFileName = when (subtopic.title) {
                    "Law of Inertia" -> "first_law"
                    "Force = Mass x Acceleration" -> "second_law"
                    "Action-Reaction" -> "third_law"
                    else -> fileBase
                }

                // Map to correct transcript JSON file names
                val transcriptFileName = when (subtopic.title) {
                    "Law of Inertia" -> "videoTranscripts/transcript_law_of_inertia.json"
                    "Force = Mass x Acceleration" -> "videoTranscripts/transcript_force_equals_mass_x_acceleration.json"
                    "Action-Reaction" -> "videoTranscripts/transcript_actionreaction.json"
                    else -> "videoTranscripts/transcript_$fileBase.json"
                }
                
                println("🔧 Generated JSON path for '${subtopic.title}': exercises/$jsonFileName.json")
                println("🎥 Generated video path for '${subtopic.title}': raw/$videoFileName")
                println("🎬 Full video URI: android.resource://${context.packageName}/raw/$videoFileName")

                materials.addAll(
                    listOf(
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.VIDEO,
                            title = subtopic.title,
                            contentPath = "android.resource://${context.packageName}/raw/$videoFileName",
                            transcript = transcriptFileName
                        ),
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.HANDS_ON,
                            title = "${subtopic.title} Exercise",
                            contentPath = "exercises/$jsonFileName.json"
                        ),
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.SIMULATION,
                            title = "${subtopic.title} Simulation",
                            contentPath = "simulations/${fileBase}_sim.json"
                        )
                    )
                )
            }

            //  Work, Power, & Energy (All have videos, hands-on, and simulation)
            val energyTitles = listOf("Work", "Power", "Energy")
            insertedSubtopics.filter { it.title in energyTitles }.forEach { subtopic ->
                val fileBase = subtopic.title.lowercase().replace(" ", "_")

                // exercises JSON file names
                val jsonFileName = when (subtopic.title) {
                    "Work" -> "hands_on_work"
                    "Power" -> "hands_on_power"
                    "Energy" -> "hands_on_energy"
                    else -> "hands_on_$fileBase"
                }
                
                // video file names
                val videoFileName = when (subtopic.title) {
                    "Work" -> "work"
                    "Power" -> "power"
                    "Energy" -> "energy"
                    else -> fileBase
                }

                // transcript JSON file names
                val transcriptFileName = when (subtopic.title) {
                    "Work" -> "videoTranscripts/transcript_work.json"
                    "Power" -> "videoTranscripts/transcript_power.json"
                    "Energy" -> "videoTranscripts/transcript_energy.json"
                    else -> "videoTranscripts/transcript_$fileBase.json"
                }
                
                println("🔧 Generated JSON path for '${subtopic.title}': exercises/$jsonFileName.json")
                println("🎥 Generated video path for '${subtopic.title}': raw/$videoFileName")
                println("🎬 Full video URI: android.resource://${context.packageName}/raw/$videoFileName")

                materials.addAll(
                    listOf(
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.VIDEO,
                            title = subtopic.title,
                            contentPath = "android.resource://${context.packageName}/raw/$videoFileName",
                            transcript = transcriptFileName
                        ),
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.HANDS_ON,
                            title = "${subtopic.title} Exercise",
                            contentPath = "exercises/$jsonFileName.json"
                        ),
                        SubtopicMaterialEntity(
                            subtopicId = subtopic.subtopicId,
                            type = MaterialType.SIMULATION,
                            title = "${subtopic.title} Simulation",
                            contentPath = "simulations/${fileBase}_sim.json"
                        )
                    )
                )
            }

            // Insert all materials for all of subtopics
            materialDao.insertMaterials(materials)


            //Load and Insert JSON Pretest and Post-test Questions for Mechanics
            try {
                val mechanicsJsonString = context.assets.open("testQuestions/questionsMechanics.json")
                    .bufferedReader().use { it.readText() }

                val mechanicsQuestionList: List<QuestionJson> = Gson().fromJson(
                    mechanicsJsonString,
                    object : TypeToken<List<QuestionJson>>() {}.type
                )

                println("✅ Successfully loaded ${mechanicsQuestionList.size} Mechanics questions")

                val mechanicsEntities = mechanicsQuestionList.map {
                    QuestionEntity(
                        id = 0,
                        lessonId = mechanicsId,
                        question = it.question,
                        choices = it.choices,
                        answer = it.answer,
                        solution = it.solution,
                        computation = it.computation
                    )
                }

                questionDao.insertQuestions(mechanicsEntities)
                println("✅ Successfully inserted ${mechanicsEntities.size} Mechanics questions to database")

            } catch (e: Exception) {
                println("❌ Error loading Mechanics questions: ${e.message}")
                e.printStackTrace()
            }

            //Load and Insert JSON Questions for Newton's Laws
            try {
                val newtonJsonString = context.assets.open("testQuestions/questionsNewtonsLaw.json")
                    .bufferedReader().use { it.readText() }

                val newtonQuestionList: List<QuestionJson> = Gson().fromJson(
                    newtonJsonString,
                    object : TypeToken<List<QuestionJson>>() {}.type
                )

                println("✅ Successfully loaded ${newtonQuestionList.size} Newton's Law questions")

                val newtonEntities = newtonQuestionList.map {
                    QuestionEntity(
                        id = 0,
                        lessonId = newtonId,
                        question = it.question,
                        choices = it.choices,
                        answer = it.answer,
                        solution = it.solution,
                        computation = it.computation
                    )
                }

                questionDao.insertQuestions(newtonEntities)
                println("✅ Successfully inserted ${newtonEntities.size} Newton's Law questions to database")

            } catch (e: Exception) {
                println("❌ Error loading Newton's Law questions: ${e.message}")
                e.printStackTrace()
            }

            //Load and Insert JSON Questions for Work/Power/Energy
            try {
                val wpeJsonString = context.assets.open("testQuestions/questionsWPE.json")
                    .bufferedReader().use { it.readText() }

                val wpeQuestionList: List<QuestionJson> = Gson().fromJson(
                    wpeJsonString,
                    object : TypeToken<List<QuestionJson>>() {}.type
                )

                println("✅ Successfully loaded ${wpeQuestionList.size} Work/Power/Energy questions")

                val wpeEntities = wpeQuestionList.map {
                    QuestionEntity(
                        id = 0,
                        lessonId = workPowerEnergyId,
                        question = it.question,
                        choices = it.choices,
                        answer = it.answer,
                        solution = it.solution,
                        computation = it.computation
                    )
                }

                questionDao.insertQuestions(wpeEntities)
                println("✅ Successfully inserted ${wpeEntities.size} Work/Power/Energy questions to database")

            } catch (e: Exception) {
                println("❌ Error loading Work/Power/Energy questions: ${e.message}")
                e.printStackTrace()
            }
        }
    }
}